### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by H4nSolo** [DracoNet/DracoNet-FivemFX#1]
Hi,

i have download and tested your GTA Server Repo.
i want to play this with my friend on my vpn network but always when he connect to server, he added automaticly in the admin group.
How i can disabled that?

Some times when my friends connected to the server and see the characker loading text on the right bottom side, the server kicked them from the Server with the messages "Timeout after 10 - 16 Seconds..." But the he have no lagg or a bad intenret connection.

Why and who i can disable that?

thanks & have a good Day

**Comment by DracoDragon88** [comment]
Hi,

The first to connect to the is added to admin so ID 1 will allways be admin.

the timeout issue might be a MySQL database 
remember to inset the Mysql in resources/vrp/base.lua and create the database with the specified name in base.lua (if not already created)
load the server so the tables will be made and then load SQL.sql in database.
