### ISSUE TITLE
[help]

### ISSUE THREAD

**Issue by Techboy12** [DracoNet/DracoNet-FivemFX#2]
hi i am using this cool pack. is there a way to add driver license to the indentity menu from vrp_dmvshool ?

**Comment by DracoDragon88** [comment]
Check last commit
https://github.com/DracoNet/DracoNet-FivemFX/commit/fac37c1c61f8ae3ccc32b934288ec9d26ef3eb2a

**Comment by Techboy12** [comment]
Working great :-)  thank you 👍
